config:
    connection:
        Google api key: AIzaSyAfr8pZMNfi8_btzWQ7A0pQEOKbQTlTPvY
        Discord bot token: Mjc4OTQxOTA4MDMyNTUyOTYx.C30Z8Q.hZeM7j47BKlmS6Rk2WHZwEfl1zM
    main:
        Ping Every x Minutes: 15 # <5 minutes NOT recommended
    YouTubers:
        0:
            name: pewdiepie
            id: pewdiepie
            channelID:
        1:
            name: jacksepticeye
            id: jacksepticeye
            channelID:
        2:
            name: WebDriver Torso
            id:
            channelID: UCsLiV4WJfkTEHH0b9PmRklw