config:
    connection:
        Google api key: 
        Discord bot token: 
    main:
        Ping Every x Minutes: 15 # <5 minutes NOT recommended
    YouTubers:
        0:
            name: pewdiepie
            id: pewdiepie
            channelID:
        1:
            name: jacksepticeye
            id: jacksepticeye
            channelID:
        2:
            name: WebDriver Torso
            id:
            channelID: UCsLiV4WJfkTEHH0b9PmRklw
